#!/usr/bin/env node
// Generates problem-bank/ (readable lists of the PRACTICE set) from the bank YAML and pattern files.
// PROBLEM_BANK_PLAN.md Section 9.2. Output is deterministic. Reserved problems are never written.
//   node scripts/bank_md.mjs          write the files
//   node scripts/bank_md.mjs --check  fail if the committed files are out of date (used by npm run build)
import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { join, relative } from 'node:path';
import { loadAll, ROOT } from './lib/load.mjs';
import { practiceByTier } from '../src/lib/validate.mjs';

const OUT = join(ROOT, 'problem-bank');
const PLATFORM_NAME = { codeforces: 'Codeforces', atcoder: 'AtCoder', cses: 'CSES', leetcode: 'LeetCode' };
const HEADER = '<!-- GENERATED by scripts/bank_md.mjs from src/data/bank/. Do not edit by hand. -->\n';
const PHASE_NAMES = ['Foundations', 'Array techniques', 'Mathematics I', 'Recursion to dynamic programming', 'Graphs', 'Range data structures', 'Strings', 'Integration'];

const esc = (s) => String(s).replace(/\|/g, '\\|');
const topicFile = (t) => `phase-${t.phase}/${t.id}-${t.slug}.md`;

function topicPage(t, bank, pf) {
  const lines = [HEADER, `# ${t.id} ${t.title}`, ''];
  lines.push(`Phase ${t.phase} (${PHASE_NAMES[t.phase]}), target rating ${t.target_rating[0]}–${t.target_rating[1]}. ` +
    `Bank status: ${bank ? bank.status.replace('_', ' ') : 'not started'}.`, '');
  if (t.id === '7.8') {
    lines.push('This topic has no practice set: all of its problems are reserved for mixed recognition sets.', '');
    return lines.join('\n');
  }
  lines.push('## Patterns', '');
  for (const p of pf.patterns) {
    lines.push(`### ${p.name} (\`${p.id}\`)`, '', p.description, '', `**Works because:** ${p.precondition}`, '');
  }
  const names = new Map(pf.patterns.map((p) => [p.id, p.name]));
  for (const tier of practiceByTier(bank, pf)) {
    lines.push(`## Tier ${tier.tier} — ${tier.name}`, '');
    if (!tier.problems.length) {
      lines.push('_No problems yet._', '');
      continue;
    }
    lines.push('| id | title | platform | difficulty | pattern |', '|---|---|---|---|---|');
    for (const p of tier.problems)
      lines.push(`| ${p.id}${p.source_check === 'api' ? ' †' : ''} | [${esc(p.title)}](${p.url}) | ${PLATFORM_NAME[p.source]} | ${esc(p.difficulty)} | ${esc(names.get(p.pattern) ?? p.pattern)} |`);
    lines.push('');
  }
  if ((bank?.problems ?? []).some((p) => p.set === 'practice' && p.source_check === 'api'))
    lines.push('† Title and rating confirmed through the Codeforces API; the statement could not be opened from the build machine, so topic fit rests on the solution note. Please spot-check.', '');
  return lines.join('\n');
}

function readme(curriculum, banks) {
  const lines = [HEADER, '# Problem bank', '',
    'Practice problems for every topic, grouped by difficulty tier (1 Warm-up, 2 Easy, 3 Core, 4 Hard, 5 Stretch) relative to each phase\'s target rating. ' +
    'Reserved problems (drills, checkpoints, reviews, exams) are deliberately not listed.', '',
    '| phase | topic | T1 | T2 | T3 | T4 | T5 | practice | status |', '|---|---|---|---|---|---|---|---|---|'];
  for (const t of curriculum) {
    const b = banks[t.id];
    const tiers = [0, 0, 0, 0, 0];
    for (const p of b?.problems ?? []) if (p.set === 'practice') tiers[p.tier - 1]++;
    const total = tiers.reduce((a, c) => a + c, 0);
    lines.push(`| ${t.phase} | [${t.id} ${esc(t.title)}](${topicFile(t)}) | ${tiers.join(' | ')} | ${total} | ${b ? b.status.replace('_', ' ') : 'not started'} |`);
  }
  lines.push('');
  return lines.join('\n');
}

const data = loadAll();
if (data.errors.length) {
  console.error('bank_md: input files are invalid; run `npm run validate` for details.');
  process.exit(1);
}
const files = new Map([['README.md', readme(data.curriculum, data.banks)]]);
for (const t of data.curriculum) files.set(topicFile(t), topicPage(t, data.banks[t.id], data.patterns[t.id]));

const existing = (dir) => (existsSync(dir) ? readdirSync(dir, { recursive: true }).map(String).filter((f) => f.endsWith('.md')) : []);

if (process.argv.includes('--check')) {
  const stale = [];
  for (const [rel, content] of files) {
    const p = join(OUT, rel);
    if (!existsSync(p) || readFileSync(p, 'utf8') !== content) stale.push(rel);
  }
  for (const rel of existing(OUT)) if (!files.has(rel.split('\\').join('/'))) stale.push(`${rel} (should not exist)`);
  if (stale.length) {
    console.error(`problem-bank/ is out of date (${stale.length} file(s)): ${stale.slice(0, 5).join(', ')}${stale.length > 5 ? ', …' : ''}`);
    console.error('Run `npm run bank:md` and commit the result.');
    process.exit(1);
  }
  console.log(`problem-bank/ is up to date (${files.size} files).`);
} else {
  rmSync(OUT, { recursive: true, force: true });
  for (const [rel, content] of files) {
    mkdirSync(join(OUT, rel, '..'), { recursive: true });
    writeFileSync(join(OUT, rel), content);
  }
  console.log(`Wrote ${files.size} files to ${relative(ROOT, OUT)}/`);
}
